package config

var (
	AWS_REGION            = "AWS_REGION"
	AWS_ACCESS_KEY        = "AWS_ACCESS_KEY_ID"
	AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"

	AWS_S3_ENDPOINT       = "AWS_S3_ENDPOINT"
	AWS_S3_SYLLABI_BUCKET = "AWS_S3_SYLLABI_BUCKET"

	AWS_SQS_ENDPOINT    = "AWS_SQS_ENDPOINT"
	AWS_SQS_WEBHOOK_URL = "AWS_SQS_WEBHOOK_URL"

	AWS_SES_ENDPOINT                = "AWS_SES_ENDPOINT"
	AWS_SES_WELCOME_TEMPLATE        = "AWS_SES_TEMPLATE_WELCOME"
	AWS_SES_UPLOAD_SUCCESS_TEMPLATE = "AWS_SES_TEMPLATE_UPLOAD_SUCCESS"
	AWS_SES_UPLOAD_ERROR_TEMPLATE   = "AWS_SES_TEMPLATE_UPLOAD_ERROR"
)
