// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jackie Li"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/courses": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Course"
                ],
                "summary": "List courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by course name or code",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category ID",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 25)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CourseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/courses/categories": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Course Category"
                ],
                "summary": "List course categories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CourseCategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/courses/categories/{categoryId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Course Category"
                ],
                "summary": "Retrieves a course category.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CourseCategoryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/courses/{courseId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Course"
                ],
                "summary": "Get a course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CourseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/faculties": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Faculty"
                ],
                "summary": "List faculties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by faculty name",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/FacultyResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/faculties/{facultyId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Faculty"
                ],
                "summary": "Get a faculty",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Faculty ID",
                        "name": "facultyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FacultyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "Removes the users session cookie if exists.",
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout user session",
                "responses": {
                    "302": {
                        "description": "Redirects to root page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "description": "Validates the session cookie and returns session payload if authenticated.",
                "tags": [
                    "Authentication"
                ],
                "summary": "Check user session",
                "responses": {
                    "200": {
                        "description": "Valid session",
                        "schema": {
                            "$ref": "#/definitions/SessionResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid session cookie",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/programs": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Program"
                ],
                "summary": "List programs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by faculty ID",
                        "name": "faculty",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by program name or code",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ProgramResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/programs/{programId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Program"
                ],
                "summary": "Get a program",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Program ID",
                        "name": "programId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ProgramResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/providers/google": {
            "get": {
                "description": "Validates an optional redirect query param and redirects the user to the OpenID login flow.",
                "tags": [
                    "Authentication"
                ],
                "summary": "Redirect to OpenID consent screen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional redirect URL after login",
                        "name": "redirect",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirects to OpenID consent screen",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unable to continue to OpenID provider",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/syllabi": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "List syllabi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by course ID",
                        "name": "courseId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by semester",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SyllabusResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "Create a syllabus",
                "parameters": [
                    {
                        "description": "Syllabus data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateSyllabusRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "URL to access the created syllabus"
                            },
                            "X-Presigned-Url": {
                                "type": "string",
                                "description": "Presigned URL to upload the syllabus file"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/syllabi/{syllabusId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "Get a syllabus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SyllabusResponse"
                        },
                        "headers": {
                            "X-Presigned-Url": {
                                "type": "string",
                                "description": "Presigned URL to access the syllabus file"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "Delete a syllabus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "Update a syllabus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated syllabus data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateSyllabusRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "URL to access the updated syllabus"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/syllabi/{syllabusId}/reaction": {
            "post": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "React to a syllabus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reaction action",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SyllabusReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "Remove syllabus reaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/syllabi/{syllabusId}/reactions": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "Syllabus"
                ],
                "summary": "List syllabus reactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Syllabus ID",
                        "name": "syllabusId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SyllabusReactionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/exists": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Check existing nickname",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search user nickname",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/NicknameExistsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "URL to access the updated user"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userId}/courses": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "List user courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search by name or course code",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category ID",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page size (default: 25)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/UserCourseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Add a user course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User course data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userId}/courses/{courseId}": {
            "delete": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete a user course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update a user course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated course data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateUserCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CourseCategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "CourseResponse": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "course": {
                    "type": "string"
                },
                "currentYear": {
                    "type": "string",
                    "x-nullable": true
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "CreateSyllabusRequest": {
            "type": "object",
            "required": [
                "checksum",
                "contentType",
                "courseId",
                "fileName",
                "fileSize",
                "semester",
                "year"
            ],
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "CreateUserCourseRequest": {
            "type": "object",
            "required": [
                "courseId"
            ],
            "properties": {
                "courseId": {
                    "type": "string"
                },
                "semesterTaken": {
                    "type": "string"
                },
                "yearTaken": {
                    "type": "integer"
                }
            }
        },
        "FacultyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "NicknameExistsResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean"
                }
            }
        },
        "ProgramResponse": {
            "type": "object",
            "properties": {
                "faculty": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "SessionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "SyllabusReactionRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                }
            }
        },
        "SyllabusReactionResponse": {
            "type": "object",
            "properties": {
                "dateReacted": {
                    "type": "integer"
                },
                "dislike": {
                    "type": "boolean"
                },
                "syllabusId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "SyllabusResponse": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "dateAdded": {
                    "type": "integer"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "received": {
                    "type": "boolean"
                },
                "semester": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "UpdateSyllabusRequest": {
            "type": "object",
            "properties": {
                "semester": {
                    "type": "string",
                    "x-nullable": true
                },
                "year": {
                    "type": "integer",
                    "x-nullable": true
                }
            }
        },
        "UpdateUserCourseRequest": {
            "type": "object",
            "properties": {
                "semesterTaken": {
                    "type": "string",
                    "x-nullable": true
                },
                "yearTaken": {
                    "type": "integer",
                    "x-nullable": true
                }
            }
        },
        "UpdateUserRequest": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "x-nullable": true
                },
                "currentYear": {
                    "type": "integer",
                    "x-nullable": true
                },
                "gender": {
                    "type": "string",
                    "x-nullable": true
                },
                "instagram": {
                    "type": "string",
                    "x-nullable": true
                },
                "nickname": {
                    "type": "string",
                    "x-nullable": true
                },
                "programId": {
                    "type": "string",
                    "x-nullable": true
                }
            }
        },
        "UserCourseResponse": {
            "type": "object",
            "properties": {
                "course": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "semesterTaken": {
                    "type": "integer",
                    "x-nullable": true
                },
                "title": {
                    "type": "string"
                },
                "yearTaken": {
                    "type": "integer",
                    "x-nullable": true
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string",
                    "x-nullable": true
                },
                "currentYear": {
                    "type": "string",
                    "x-nullable": true
                },
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "gender": {
                    "type": "string",
                    "x-nullable": true
                },
                "id": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string",
                    "x-nullable": true
                },
                "nickname": {
                    "type": "string",
                    "x-nullable": true
                },
                "picture": {
                    "type": "string",
                    "x-nullable": true
                },
                "programId": {
                    "type": "string",
                    "x-nullable": true
                }
            }
        }
    },
    "securityDefinitions": {
        "Session": {
            "type": "apiKey",
            "name": "syllabye.session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Syllabye API",
	Description:      "Syllabye API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
