definitions:
  model.Session:
    properties:
      id:
        type: string
      userId:
        type: string
    type: object
info:
  contact:
    name: Jackie Li
  description: Syllabye API server.
  title: Syllabye API
  version: "1.0"
paths:
  /me:
    get:
      description: Validates the session cookie and returns session payload if authenticated.
      responses:
        "200":
          description: Valid session
          schema:
            $ref: '#/definitions/model.Session'
        "401":
          description: Missing or invalid session cookie
          schema:
            type: string
      security:
      - Session: []
      summary: Check user session
      tags:
      - Authentication
  /providers/google:
    get:
      description: Validates an optional redirect query param and redirects the user
        to the OpenID login flow.
      parameters:
      - description: Optional redirect URL after login
        in: query
        name: redirect
        type: string
      responses:
        "302":
          description: Redirects to OpenID consent screen
          schema:
            type: string
        "500":
          description: Unable to continue to OpenID provider
          schema:
            type: string
      summary: Redirect to OpenID consent screen
      tags:
      - Authentication
  /providers/google/callback:
    get:
      description: Validates authorization code and state, registers or logs in user,
        and sets session cookie.
      parameters:
      - description: Authorization code returned by the OpenID provider
        in: query
        name: code
        required: true
        type: string
      - description: State token for CSRF protection and redirect tracking
        in: query
        name: state
        required: true
        type: string
      responses:
        "302":
          description: Redirects to dashboard or original destination
          schema:
            type: string
        "401":
          description: Invalid or expired state token
          schema:
            type: string
        "500":
          description: Token exchange, validation, or session creation failed
          schema:
            type: string
      summary: OpenID provider callback
      tags:
      - Authentication
securityDefinitions:
  Session:
    in: cookie
    name: syllabye.session
    type: apiKey
swagger: "2.0"
